language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: In2jCFEcVLejTSzGyT9wG9Krzl75Gb0MDC5HJlhxCxJpTqFP9vOjRiRaB4a3B8PxHadDEENYSf1590qyWIkwU3EJX3SGdt/wxktp+8VVKRbbiClfEPq34GdLXQjRwCbLHaUT7n7BX2lvm1CNMCqOlQf2Hv3OxeYlNJUgrl+AkBgsZ+08/jogshfZbMiaWCain4lDB0s/WhA+7Lg2GPMXUTccGYQDl3ayoNpRbLi2oA4MUMdw8g9EM3w3wwEn0YfbjfjeIQReaJaltkKFBStqyiXAtq1JfHz6dDKzGuhyFfqN40dyvx3W+2tDjiOYP94KWRB7SydQuDtKyqSPspVnK76llrWN8IXXLpReulTljBjgHSC3pJVEHW9I8ktBhAb7leRjUUMLsQIF88KekSDb+2V8f/9aoPUI9y/E0xZp86S9vnB3W8fUji3tFxq8FdOT5/Na/MlJLHYNRT9MOtvZkeGVxlAjYUuWq2dZ2YBaVov8K4E7PQ4DUjdJVonrC2aqQoGg3/0wFQGUyF+EbajGUIMutJQglQHgRo9fFC6ycpJTgpNko3A8pQZvesWHEASiS4p3qpv5Cxq7sMLHVnmLWecX15/JTL8dWfiKkxPqk1Nn7CnmwuShOc3gXRqzFRVuqIxttnQWz2DqFaz1Sh0HkQepJvHzCgBleySLQIg+Ktk=
  app: murmuring-earth-28698
  on:
    repo: grahamwh/gymnacity-api
